### ISSUE TITLE
Ready for grading, Week 9 Functions lab.  f2c.py and tempconversion.py

### ISSUE THREAD

**Issue by ajjacques-matc** [madisoncollege-it-programs/python-scripting-ajjacques-matc#11]

**Comment by cethenmc** [comment]
Hi, Tony.  I will record a 6 of 8 for now.  You can resubmit for full credit.  Just reply to this same ticket when it is ready to regrade.  These were missed in the first script.  

![image](https://user-images.githubusercontent.com/112707666/200025073-ed6a86d2-c892-4260-b1c6-76fd0872ac4b.png)

I will also add that you _could_ run the tempconversion.py through its own "main()" function.  The heading of the week 9 lab very poorly indicates it in parentheses  "Script 2 - Temp Conversion (**Main**)."  You may consider modifying your tempconversion.py script or creating another (tempconversion2.py) where it will use \_\_name\_\_ to ensure the main() function runs.  Your main() function would simply include the code in your script.

As always, please book me if you would like to go through any of this feedback.

**Comment by cethenmc** [comment]
Hi Tony - Are you keeping the 6 out of 8 or are you resubmitting corrections on this lab?

**Comment by cethenmc** [comment]
Closing ticket.  With a great job on the final exam, you secured an A without needing corrections on this lab!
