### ISSUE TITLE
Still missing Week#2 Assignment #1

### ISSUE THREAD

**Issue by cethenmc** [madisoncollege-it-programs/python-scripting-ajjacques-matc#3]
Tony - You submitted only one issue for Week 2 assignments.  There were two assignments, of which you only did the second of 2.  I indicated this information in your Issue, but you closed the ticket.  Will you please complete Week 2, Assignment #1.  However, don't restore way back to your first commit.  You will need to restore to your current commit point so that you don't lose any later assignments you already completed.  Thanks. ~Chris

**Comment by ajjacques-matc** [comment]
Hi Chris - Not sure how I missed the second part of the Week 2 assignment, but it should be complete now.

**Comment by cethenmc** [comment]
Finally reviewed.  Again, please do NOT close tickets yourself.  I will close once I grade. Full credit recorded now.
