### ISSUE TITLE
Week 5 files assignment ready for grading.

### ISSUE THREAD

**Issue by ajjacques-matc** [madisoncollege-it-programs/python-scripting-ajjacques-matc#5]

**Comment by cethenmc** [comment]
Tony - A couple of issues, so I would like you to correct and resubmit.

- #2C missing.  I don't see an answer for 2C.
- #3 you are not saving the full file contents into a variable.
- #3B will you please reference for me where it says where reading the whole file line by line would reduce memory.  If you are correct, then I would like to give you credit.  There is the next() function for which your statement is true, but I am not so sure for readline().  If you cannot find a source to give proof to your answer in 3B about it using less memory, I will gladly take another issue.

Please resubmit.  I will record a 5 of 8 for now in the grade book, but I will gladly take a resubmit.  ~Chris

**Comment by cethenmc** [comment]
Hi, Tony.  Please be sure to resubmit week 5.

#2C missing. I don't see an answer for 2C.
#3 you are not saving the full file contents into a variable.
#3B will you please reference for me where it says where reading the whole file line by line would reduce memory. If you are correct, then I would like to give you credit. There is the next() function for which your statement is true, but I am not so sure for readline(). If you cannot find a source to give proof to your answer in 3B about it using less memory, I will gladly take another issue

**Comment by ajjacques-matc** [comment]
> Tony - A couple of issues, so I would like you to correct and resubmit.
> 
> * #2C missing.  I don't see an answer for 2C.
> * [Still missing Week#2 Assignment #1 #3](https://github.com/madisoncollege-it-programs/python-scripting-ajjacques-matc/issues/3) you are not saving the full file contents into a variable.
> * #3B will you please reference for me where it says where reading the whole file line by line would reduce memory.  If you are correct, then I would like to give you credit.  There is the next() function for which your statement is true, but I am not so sure for readline().  If you cannot find a source to give proof to your answer in 3B about it using less memory, I will gladly take another issue.
> 
> Please resubmit. I will record a 5 of 8 for now in the grade book, but I will gladly take a resubmit. ~Chris

Hi Chris:
I'll accept the points that you assigned for this one. --Tony

**Comment by cethenmc** [comment]
Locked in grade.  Closing ticket.
