### ISSUE TITLE
week 6 flowcontrol and boolean assignments ready for grading

### ISSUE THREAD

**Issue by ajjacques-matc** [madisoncollege-it-programs/python-scripting-ajjacques-matc#6]

**Comment by cethenmc** [comment]
Tony - Thanks for handing in the work. 
1) Recorded 0 of 8 just for now, and will update after resubmitted.  The output from executing the boolean.py script should be printing out 19 True or False's based on how the expression evaluates.  For example,
True
True
False
True
False
2) Recorded  4 of 8 for now.  The flowcontrol.py is not finished
**You enter a dark room with two doors. 
Do you go through door #1 or door #2?
->** 
You are not prompting for a third door at the top level like instructions called for.  Also Door 3 was not made differently.  Door 1 content was copied and left.

PLEASE reply to this ticket when the assignments are

**Comment by cethenmc** [comment]
1. Thanks, for correcting **boolean.py**. (this one is now switched to full credit).
2. Please look at previous feedback in my last reply regarding **flowcontrol.py**.  That needs to be corrected still.

PLEASE reply to this issue ticket when it is ready for grading your corrections.

Thanks.

Chris

**Comment by ajjacques-matc** [comment]
Chris - I have added some additional logic to the flowcontrol script for the door #3.

**Comment by cethenmc** [comment]
Great work!  Full credit earned!
